=== mouradlabidi/EditeurXml/example.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="courses">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="course" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:all>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="price" type="xsd:double"/>
                        </xsd:all>
                        <xsd:attribute name="id" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== mouradlabidi/EditeurXml/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="example.xsd">
  
    <course id="1">
        <name>JDOM XSD Validation</name>
        <price>0.0</price>
    </course>
    <course id="2">
        <name>Validate XML against XSD Schema</name>
        <price>0.0</price>
    </course>
    <course id="3">
        <name>
            <![CDATA[
               characters & ? $ ^ with markup
            ]]>
        </name>
        <price>12.0</price>
    </course>
</courses>
