=== mouradlabidi/EditeurXml/galerie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:element  name="contenu">
       <xs:complexType>
          <xs:sequence>
             <xs:element name="type" type="xs:string" />
             <xs:element name="auteur" type="xs:string" />
             <xs:element name="titre" type="xs:string" minOccurs="0" />
             <xs:element name="prix" type="xs:double" minOccurs="0" />
          </xs:sequence>
       </xs:complexType>
   </xs:element>
   
   <xs:element  name="galerie">
       <xs:complexType>
          <xs:sequence>
             <xs:element name="gerant" type="xs:string" />
             <xs:element ref="contenu" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
          <xs:attribute name="adresse" type="xs:string" use="required" />
       </xs:complexType>
   </xs:element>

   <xs:element name="galeries">
      <xs:complexType>
          <xs:sequence>
             <xs:element ref="galerie" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
       </xs:complexType>
   </xs:element>
</xs:schema>

=== mouradlabidi/EditeurXml/galerie.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<galeries xs:noNamespaceSchemaLocation="galerie.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
<galerie adresse="3 rue du bourg 22250 TREMEUR">
<gerant>Jean CAISSE</gerant>
<contenu>
<type>sculpture</type>
<auteur>Rodin</auteur>
<titre>Le penseur</titre>
<prix>25</prix>
</contenu>
<contenu>
<type>peinture</type>
<auteur>Herby Cyrille</auteur>
<titre>Ma peinture</titre>
</contenu>
</galerie>
<galerie adresse="24 boulvard de Svign 75000 PARIS">
<gerant>Marc MOISSA</gerant>
<contenu>
<type>sculpture</type>
<auteur>Tony Williams</auteur>
<prix>123.25</prix>
</contenu>
<contenu>
<type>canevas</type>
<auteur>Mamy HERBY</auteur>
<titre>Mon coussin</titre>
<prix>12</prix>
</contenu>
</galerie>
</galeries>
